ERROR      2024-12-12 11:36:16,675 [main.py:95] データをクリーニング中に何らかのエラーが発生しました
ERROR      2024-12-12 14:17:51,231 [main.py:82] データをクリーニング中に何らかのエラーが発生しました
ERROR      2024-12-12 14:20:19,166 [main.py:83] データをクリーニング中に何らかのエラーが発生しました
ERROR      2024-12-12 14:21:26,515 [main.py:83] データをクリーニング中に何らかのエラーが発生しました
ERROR      2024-12-12 14:23:30,742 [main.py:83] データをクリーニング中に何らかのエラーが発生しました
